title: Design Systems Repo
email: jadlimcaco@gmail.com
description: An organized and frequently updated collection of Design System examples, resources, tools, articles and videos.
baseurl:
url: "https://designsystemsrepo.com"
twitter_username: jadlimcaco
github_username:  jadlimcaco
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-responsive-image
  - jekyll-srcset

compress_html:
  comments: all

permalink: pretty

collections:
  tools:
    output: true
  articles:
    output: true
  design-systems:
    output: true
  books:
    output: true
  talks:
    output: true